name: Scheduled API Call

on:
  workflow_dispatch:  # 保留此行以启用手动触发
  schedule:
    - cron: '0 * * * *'  # 每1分钟执行一次

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Call the API
      run: |
        curl -X GET https://vercel-api-123.vercel.app/api/upload