name: Scheduled API Call

on:
  workflow_dispatch:  # 添加此行来启用手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时的第0分钟执行

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Call the API
      run: |
        curl -X GET https://vercel-api-123.vercel.app/api/upload